# Generated by Django 4.1 on 2022-12-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221003_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('Food_Plan_Summary_week_one', models.CharField(max_length=500, null=True)),
                ('Food_Plan_Summary_week_one_chart', models.ImageField(null=True, upload_to=None)),
                ('Food_Plan_Summary_week_two', models.CharField(max_length=500, null=True)),
                ('Food_Plan_Summary_week_two_chart', models.ImageField(null=True, upload_to=None)),
                ('Food_Plan_Summary_week_three', models.CharField(max_length=500, null=True)),
                ('Food_Plan_Summary_week_three_chart', models.ImageField(null=True, upload_to=None)),
                ('Food_Plan_Summary_week_four', models.CharField(max_length=500, null=True)),
                ('Food_Plan_Summary_week_four_chart', models.ImageField(null=True, upload_to=None)),
                ('Training_Plan_Summary_week_one', models.CharField(max_length=500, null=True)),
                ('Training_Plan_Summary_week_one_chart', models.ImageField(null=True, upload_to=None)),
                ('Training_Plan_Summary_week_two', models.CharField(max_length=500, null=True)),
                ('Training_Plan_Summary_week_two_chart', models.ImageField(null=True, upload_to=None)),
                ('Training_Plan_Summary_week_three', models.CharField(max_length=500, null=True)),
                ('Training_Plan_Summary_week_three_chart', models.ImageField(null=True, upload_to=None)),
                ('Training_Plan_Summary_week_four', models.CharField(max_length=500, null=True)),
                ('Training_Plan_Summary_week_four_chart', models.ImageField(null=True, upload_to=None)),
                ('Buy_week_one', models.CharField(max_length=500, null=True)),
                ('Buy_week_one_chart', models.ImageField(null=True, upload_to=None)),
                ('Buy_week_two', models.CharField(max_length=500, null=True)),
                ('Buy_week_two_chart', models.ImageField(null=True, upload_to=None)),
                ('Buy_week_three', models.CharField(max_length=500, null=True)),
                ('Buy_week_three_chart', models.ImageField(null=True, upload_to=None)),
                ('Buy_week_four', models.CharField(max_length=500, null=True)),
                ('Buy_week_four_chart', models.ImageField(null=True, upload_to=None)),
                ('Progress_week_one', models.CharField(max_length=500, null=True)),
                ('Progress_week_one_chart', models.ImageField(null=True, upload_to=None)),
                ('Progress_week_two', models.CharField(max_length=500, null=True)),
                ('Progress_week_two_chart', models.ImageField(null=True, upload_to=None)),
                ('Progress_week_three', models.CharField(max_length=500, null=True)),
                ('Progress_week_three_chart', models.ImageField(null=True, upload_to=None)),
                ('Progress_week_four', models.CharField(max_length=500, null=True)),
                ('Progress_week_four_chart', models.ImageField(null=True, upload_to=None)),
                ('My_measurements_and_progress', models.CharField(max_length=500, null=True)),
                ('The_summary_of_the_progression_curve', models.CharField(max_length=500, null=True)),
                ('Meal_close_to_the_training_summary', models.CharField(max_length=500, null=True)),
                ('Pre_post_recipe_data', models.CharField(max_length=500, null=True)),
                ('In_Case_recipe_data', models.CharField(max_length=500, null=True)),
                ('Meal_away_training_recipe_data', models.CharField(max_length=500, null=True)),
                ('Dessert_recipe_data', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
